name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build config'
        required: true
        type: choice
        default: Release
        options:
          - Debug
          - Release
      branchName:
        description: 'Target branch to build'
        default: master
        required: false
        type: string

jobs:
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      buildType: ${{steps.assign_build_input.outputs.buildType}}
      branchName: ${{steps.assign_branch_input.outputs.branchName}}

    steps:
      - name: Check buildType Input
        id: assign_build_input
        run: echo "::set-output name=buildType::${{(github.event.inputs.buildType||'Release')}}"

      - name: Check branchName Input
        id: assign_branch_input
        run: echo "::set-output name=branchName::${{(github.event.inputs.branchName||'master')}}"

      - name: Validate Inputs
        id: check_input_vals
        run: echo "{branchName:${{github.event.inputs.branchName}}, buildType:${{github.event.inputs.buildType}}}"

      - name: Validate Outputs
        id: check_output_vals
        run: echo "{branchName:${{steps.assign_branch_input.outputs.branchName}}, buildType:${{steps.assign_build_input.outputs.buildType}}}"

  build-ubuntu-latest:
    needs: [env-setup]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: ubuntu-latest
      branchName: ${{needs.env-setup.outputs.branchName}}
      buildType: ${{needs.env-setup.outputs.buildType}}

  build-windows-latest:
    needs: [env-setup]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: windows-latest
      branchName: ${{needs.env-setup.outputs.branchName}}
      buildType: ${{needs.env-setup.outputs.buildType}}